name: default

on:
  push:
    branches-ignore:
      - main
      - dev
    tags-ignore:
      - '**'

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      UV_PYTHON: "3.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.43.3

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.UV_PYTHON }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.UV_PYTHON }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev --all-packages

      - name: Lint commit message
        run: |
          pip install gitlint
          git log -1 --pretty=%B | gitlint

      - name: Lint code
        run: task python:lint
