name: release

on:
  push:
    tags: ["*"]

jobs:
  publish-library:
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      github.repository == 'wizrds/vectorm'
    name: Publish library to pypi
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      UV_PYTHON: "3.14"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.UV_PYTHON }}

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.43.3

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.UV_PYTHON }}

      - name: Install dependencies
        run: uv sync --all-extras --dev --all-packages

      - name: Build library
        run: uv run task python:build

      - name: Publish to PyPI
        # run: task python:publish
        run: echo "Publishing to PyPI"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

  make-release:
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      github.repository == 'wizrds/vectorm'
    needs: [publish-library]
    name: Create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.43.3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts

      - name: Extract changelog for release
        id: changelog
        run: |
          TAG=$(task version:current)
          PREV_VERSION=$(grep -E '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md | head -n 2 | tail -n 1 | sed -E 's/^## \[([^]]+)\].*/\1/')
          
          awk -v tag="$TAG" '
            # Start when we hit the current version header
            $0 ~ "^## \\[" tag "\\]" { printing=1; next }

            # Stop when we hit the next version header
            printing && $0 ~ "^## \\[" { exit }

            printing
          ' CHANGELOG.md > release_notes.md
          
          echo "Release notes for $TAG:"
          cat release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}